global:
  scrape_interval: 15s  # Collecte des métriques toutes les 15 secondes

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Remplacer par ton endpoint
